owner: daniel-law
repo: future-lab-status

sites:
  - name: Portfolio
    url: https://daniellaw.me
  - name: Frugality
    url: https://frugality.app
  - name: Kurisu
    url: https://kurisu.future-lab.uk
assignees:
  - daniel-law
status-website:
  baseUrl: /future-lab-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Future Lab
  introTitle: "**Lab Status**"
  themeUrl: https://daniel-law.github.io/future-lab-status/lab.css
  links:
    - rel: stylesheet
      href: https://daniel-law.github.io/future-lab-status/custom-styles.css
i18n:
  footer: Future Lab Monitoring Service.
