owner: daniel-law
repo: future-lab-status

sites:
  - name: Portfolio
    url: https://daniellaw.me
  - name: Frugality
    url: https://frugality.app
  - name: Kurisu
    url: https://kurisu.future-lab.uk
assignees:
  - daniel-law
status-website:
  logoUrl: https://future-lab.uk/future-lab-icon.png
  favicon: https://future-lab.uk/favicon.ico
  cname: future-lab.uk
  name: Future Lab
  introTitle: "**Future Lab**"
  themeUrl: https://future-lab.uk/lab.css
  links:
    - rel: stylesheet
      href: https://future-lab.uk/custom-styles.css
i18n:
  footer: Future Lab monitoring service.
  liveStatus: Status by Service